# Generated by Django 4.1.4 on 2023-01-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0004_remove_student_year_in_school_student_javobi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Savollar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savol', models.CharField(max_length=255)),
                ('manbaa', models.CharField(max_length=255)),
                ('javob_1', models.CharField(max_length=55)),
                ('javob_2', models.CharField(max_length=55)),
                ('javob_3', models.CharField(max_length=55)),
                ('javob_4', models.CharField(max_length=55)),
                ('javobi', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_category', to='all.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
