# Generated by Django 4.1.4 on 2023-01-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0005_category_savollar_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savollar',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Savollar',
        ),
    ]
